language: node_js
script: echo "do nothing"
deploy:
  provider: s3
  access_key_id:
    secure: peMMT9tFfaf6KGFfpM+5WRyLw8HfpQUh8f4Ku5M8DE3yZc+lo0Lr2DPDCd3CuUe/VyFgO30KTefy0U6SiIYWfvoqt3BwlFvnXEFUEwv1hBUA8wv4AAEijq4t2SotuUhziZIe8yOcTRF+bNnIe7NhCwpSWcbJYRGfX/2I7gFIpHE+aVHkjrvKM0QhcCEF1WE0F83Z0WHwqIBG4knbE4XqYpJpZXGxWs+yBfmv98LlTdB8SwWXlfck5jSLxHcNKDnEnQHqJDr/KSaTyrh2PVw8Kgu51TBZY1cWBqxN7CjUn3tCAyOnxdjKGK/kKNLNOUADIFv1sTPcnkuzcR6jP1gDRdKZ6hCoC5nSGl/nPBICBgmsXUG6Zl6k3n8iD4Yh4cuOhM0r4XoJ+jLywHqTYMaSx34iIiBV5xHP5w7YhsLDPSBJqH/QVxuCV+D8XbME8IU1Rg8a9onhQHcIrw0dIFAEX9xtD+L2ZsapFKDLrjxJ8hG8Be+X1rKJWyu93kStlsqH4EOO6vwOfowEe4fq2n1fH8BXG7+S4Cs00Xo5lZfyuEq1VWsvxxunX23tVjzu2K7q59P2Zeq3v/SN/wFmutGQOmm5599jjx05dUtuwAGEnk6eDego3StaJ0FjxiV1CTxrhEGjgMpXn6maeEruOu0+6sH1MPFb5O8xeV3KeH1FaxI=
  secret_access_key:
    secure: "sMZvI7Ps9paq6lrKhiNxnAd0jl6RZAMhMJ8dxGqosMbyPCTanvgjG4Hm296B9fjF61JtG0NfyNeJZnRiBjg3bcjRIQ63YKuzffxopDd+FhiXpFM7LDwLiZys0F/RgO4yV4YRc8hNGFiD1QUkLAzz82kLkdVJKwFFtrfz9ciNmkjm9nqgw+ueHgmg1nNnG2tvkvdRmk20d4QczPpnCDU+CdBzmc74F0JJH8FxgDS2eCrhiSokle+Gu6/KM5VEXfdylk65HhG94keKmZYHwYYMAGBsSoaeNACgqV0AP8t0AMYIiPen6dZwKsQArFcLO9YlWwNNCwPaj6BPs+M3tpepFKkHkQKo4L+ayjp/DtibqH9A9H/4cbiM1OqYsx3PhbAhMioDd7949X+4YlXwIAh4vIinWIbrE+mTDeHIKHKyRyDcVKpg/tfKVMyZAnbX5EILvpiYwSBCgT9jeDV5EuFipuSuNEv97rdvOjLnY0eFdKBY04uL5hoS11gf4pOtjuPngrKwGpRurr9j6c3UwsqMuh+mm/wixGAzOGDMBKjcwG+PaXgtB14kwwzZabo0tcUF13X/HUy9yitcuSWrfV7ffaLOYPfaJyYT1TvIh1YUbBmLMB5kPBFbUBk+e5JR0bOuHkdczehoONWINTH3m/GbB/vIB0cQfc5IuPGupkZ+i0k="
  bucket: shikumi-zukuri.com
  skip_cleanup: true
  region: ap-northeast-1
  endpoint: s3.amazonaws.com
  on:
    branch: master
