language: node_js
script: echo "do nothing"
deploy:
  provider: s3
  access_key_id:
    secure: peMMT9tFfaf6KGFfpM+5WRyLw8HfpQUh8f4Ku5M8DE3yZc+lo0Lr2DPDCd3CuUe/VyFgO30KTefy0U6SiIYWfvoqt3BwlFvnXEFUEwv1hBUA8wv4AAEijq4t2SotuUhziZIe8yOcTRF+bNnIe7NhCwpSWcbJYRGfX/2I7gFIpHE+aVHkjrvKM0QhcCEF1WE0F83Z0WHwqIBG4knbE4XqYpJpZXGxWs+yBfmv98LlTdB8SwWXlfck5jSLxHcNKDnEnQHqJDr/KSaTyrh2PVw8Kgu51TBZY1cWBqxN7CjUn3tCAyOnxdjKGK/kKNLNOUADIFv1sTPcnkuzcR6jP1gDRdKZ6hCoC5nSGl/nPBICBgmsXUG6Zl6k3n8iD4Yh4cuOhM0r4XoJ+jLywHqTYMaSx34iIiBV5xHP5w7YhsLDPSBJqH/QVxuCV+D8XbME8IU1Rg8a9onhQHcIrw0dIFAEX9xtD+L2ZsapFKDLrjxJ8hG8Be+X1rKJWyu93kStlsqH4EOO6vwOfowEe4fq2n1fH8BXG7+S4Cs00Xo5lZfyuEq1VWsvxxunX23tVjzu2K7q59P2Zeq3v/SN/wFmutGQOmm5599jjx05dUtuwAGEnk6eDego3StaJ0FjxiV1CTxrhEGjgMpXn6maeEruOu0+6sH1MPFb5O8xeV3KeH1FaxI=
  secret_access_key:
    secure: Q8J0w3jVankgr9AGQ5B3GAInVItHst04zQCycDobMfw6iac5TZ56xDR8IFpPGwCfU6Eh4F7bpTrQzbrlT+8JvlJI7UEqzWBLU9NWiYEBFszcmZJe/1J7fomZWJRIJqkuEcmDbwwoZibPEEEEb0M5oAll6FdKmoSIXY1wQw0KysFxmBH/rRPchLUW6VEQFizd0sreJSOZz0muNViU6ZIh5psD7Jab5wmchMxczRycwtYFsEoEHDFzD4UCPVr65a+3eeWjfAsS/xK13+NSv0n5PKI8/rkb6z9Mnl7T067ewQ/PO78WlA80KUGkVjzt8h92EddvYKjoPFNPwfD/fchRBfU5F7PJxiP22i/0G4/9c9uJiPyxHIppdOisnIIMmWmE4xhZByPEhrFj2KqmsFT7If7To8Uhs+MwQIglA3z0CmT3UOzd3ap0W4Htky3tJwZwM3OVBEPOsv/1zzAa0wDLCKE5bWdHsgKcr7PR8GnvZb7ORTsZ/pK93vmlaq+GdeeaZHOFiVqNwurFN5ZyJhrmOUnwydshQjoQlGUC0/e2vCryVozk3nE1yPRwcylshlHUah3p4IgsTX9CrXbUtrG+DRMF0CY1y4obtH/igLzhUAKj+k0TkkSxpmF5SyAXsTa4ba7yNP2xAgJN+EBnq+RJ63nym3RMrKaL2DuRVNMj+Lo=
  bucket: shikumi-zukuri.com
  skip_cleanup: true
  region: ap-northeast-1
  endpoint: s3.amazonaws.com
  on:
    branch: master
